### ISSUE TITLE
Doesn't work with Django 1.9

### ISSUE THREAD

**Issue by chrismytton** [mysociety/django-info-pages#9]
Seeing the following tests failures when using Django 1.9.13

```
$ python runtests.py
Creating test database for alias 'default'...
....EE........
======================================================================
ERROR: test_categories (info.tests.InfoBlogClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chris/Code/mysociety/django-info-pages/info/tests.py", line 374, in test_categories
    url_base = '/blog/category/'
  File "/Users/chris/Code/mysociety/django-info-pages/info/tests.py", line 347, in _test_label
    response = c.get(url)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 503, in get
    **extra)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 304, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 380, in generic
    return self.request(**r)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 467, in request
    six.reraise(*exc_info)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/library.py", line 223, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/pagination/templatetags/pagination_tags.py", line 144, in paginate
    first = set(page_range[:window])
TypeError: sequence index must be integer, not 'slice'

======================================================================
ERROR: test_tags (info.tests.InfoBlogClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chris/Code/mysociety/django-info-pages/info/tests.py", line 364, in test_tags
    url_base = '/blog/tag/'
  File "/Users/chris/Code/mysociety/django-info-pages/info/tests.py", line 347, in _test_label
    response = c.get(url)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 503, in get
    **extra)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 304, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 380, in generic
    return self.request(**r)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/client.py", line 467, in request
    six.reraise(*exc_info)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/django/template/library.py", line 223, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/chris/.local/share/virtualenvs/django-info-pages/lib/python2.7/site-packages/pagination/templatetags/pagination_tags.py", line 144, in paginate
    first = set(page_range[:window])
TypeError: sequence index must be integer, not 'slice'

----------------------------------------------------------------------
Ran 14 tests in 0.290s

FAILED (errors=2)
Destroying test database for alias 'default'...
```

**Comment by chrismytton** [comment]
It seems that this is an issue with django-pagination, which hasn't had a new release [since 2010](https://pypi.org/project/django-pagination/#history). There are a few options:

- Use one of the django-pagination forks that fix Django compatibility: [erickpeirson/django-pagination](https://github.com/erickpeirson/django-pagination) makes the minimal changes possible for newer Django compatibility, from what I can see. [krallin/django-pagination](https://github.com/krallin/django-pagination) seems to have quite a few changes to make it compatible with newer Django.
- Use [pydanny/dj-pagination](https://github.com/pydanny/dj-pagination), which is a rewrite, so wouldn't be a drop in replacement
- Remove the django-pagination dependency and use something else, e.g. Django's built in pagination (not sure why this wasn't used in the first place?)
- Create a mysociety fork of django-pagination which fixes the problems we're facing
